site_name: Hara-Lab Home Page
nav:
  - Home: index.md
  - About: about.md
  - Member: member.md
  - English:
    - Home: index.md
    - About: about-e.md
    - Member: member-e.md
theme:
  name: 'material'
  language: 'ja'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
extra:
  search:
    language: 'jp'
markdown_extensions:
  - admonition
  - footnotes
  - codehilite
  - toc:
      permalink: true
  - pymdownx.tasklist:  
      custom_checkbox: true
